# Site settings
title: Watchiot Docs API
email: dev@watchiot.org
description: "Watchiot Docs API"
baseurl: ""
url: "http://www.watchiot.org"

# Build settings
markdown: kramdown
permalink: "/:categories/:title/"
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
