title: Watchiot Docs
email: dev@watchiot.org
description: "Watchiot Docs"
baseurl: ""
url: "http://www.watchiot.org"
url_api: "http://api.watchiot.org"
url_config: "http://repo.watchiot.org"
url_notif: "http://notif.watchiot.org"

markdown: kramdown
gems: ['kramdown']

highlighter: rouge

permalink: /:title/

# Plugins
gems: 
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["en", "es"]

exclude_from_localizations: ["javascript", "images", "css", "Gemfile", "scripts", "favicon.ico", "LICENSE", "README.md"]

# Build settings
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']