# Site settings
title: Watchiot Docs API
email: dev@watchiot.org
description: "Watchiot Docs API"
baseurl: ""
url: "http://watchiot.org"
twitter_username: gorums_hack
github_username:  gorums

# Build settings
markdown: kramdown
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
